import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";

import { Poppins } from "next/font/google"; // Correct import path for fonts in Next.js 13+

// Load Poppins font with subsets
const poppinsFont = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Specify weights
  subsets: ["latin"], // Specify subsets
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppinsFont.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
